accounts/urls.py
""" Defines URL pattern for accounts """

from django.urls import path
from . import views

urlpatterns=[
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
    path('register/', views.register, name="register"),
]

meal_planner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meal_planners.urls')),
    path('accounts/', include('accounts.urls')),
]

meal_planners/urls.py
""" Defining url patterns for app """

from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('planner/', views.planner, name='planner'),
    path('meal_time/<int:day_id>/', views.meal_time, name='meal_time'),
    path('add_day/', views.add_day, name='add_day'),
    path('add_meal_time/<int:day_id>/', views.add_meal_time, name='add_meal_time'),
    path('add_meal/<int:meal_time_id>/', views.add_meal, name='add_meal'),
]

accounts/models.py
from django.db import models

# Create your models here.

meal_planners/models.py
from django.db import models


class Day(models.Model):
    """ This class handles the text day """

    text = models.CharField(max_length=30)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text
    

class MealTime(models.Model):
    """ This class handles the text meal time """

    day = models.ForeignKey(Day, on_delete=models.CASCADE)
    text = models.CharField(max_length=30)

    def __str__(self):
        return self.text
    

class Meal(models.Model):
    """ This class handles the text meal """

    meal_time = models.ForeignKey(MealTime, on_delete=models.CASCADE)
    text = models.CharField(max_length=90)

    def __str__(self):
        return self.text

accounts/forms.py
from django import forms


class LoginForm(forms.Form):
    """ class defines the form for login creds """

    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput)
    

meal_planners/forms.py
from django import forms
from .models import Day, MealTime, Meal

class DayForm(forms.ModelForm):
    """ This class will create a form for the day model """

    class Meta:
        """ Specifying which fields are allowed and labels """
        model = Day
        fields = ['text']
        labels = {'text':''}


class MealTimeForm(forms.ModelForm):
    """ This class will create a form for the meal time """

    class Meta:
        """ Specifying which fields are allowed and labels """
        model = MealTime
        fields = ['text']
        labels = {'text':''}


class MealForm(forms.ModelForm):
    """ This class will create a form for the meal """

    class Meta:
        """ Specifying which fields are allowed and labels """
        model = Meal
        fields= ['text']
        labels = {'text':''}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from .forms import LoginForm

def login_view(request):
    """ This view will render the login form """

    if request.method == 'POST':
        # POST Data Submitted; process data
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            
            if user is not None:
                login(request, user)
                return redirect('home')
    else:
        # No Data Submitted; create blank form
        form = LoginForm()
    
    context = {'form':form}
    return render(request, 'accounts/login.html', context)


def logout_view(request):
    """ This view will render the logout system """

    logout(request)
    return redirect('login_view')


def register(request):
    """ This view will render the loog """

    if request.method == 'POST':
        # POST Data Submitted; process data
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            user = authenticate(username=new_user.username, password=request.POST['password1'])
            if user is not None:
                # logging in new user
                login(request, user)
                return redirect('home')
    else:
        # No Data Submitted; create blank form
        form = UserCreationForm()
    
    context = {'form':form}
    return render(request, 'accounts/register.html', context)

meal_planners/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Day, MealTime
from .forms import DayForm, MealTimeForm, MealForm

def home(request):
    """ This view will render the home page """
    return render(request, 'meal_planners/home.html')


def planner(request):
    """ This view will render the full meal planner page """

    days = Day.objects.all()
    context = {'days':days}
    return render(request, 'meal_planners/planner.html', context)


def meal_time(request, day_id):
    """ This view will render the meal times """

    day = get_object_or_404(Day, pk=day_id)
    meal_times = day.mealtime_set.all()
    context = {'day':day, 'meal_times': meal_times}
    return render(request, 'meal_planners/day_meal_plan.html', context)


def add_day(request):
    """ This view will render a form to add a day """

    if request.method != 'POST':
        # No Data Submitted; create a blank form
        form = DayForm()
    else:
        # POST Data Submitted; process data
        form = DayForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('planner'))
    
    context = {'form':form}
    return render(request, 'meal_planners/add_day.html', context)


def add_meal_time(request, day_id):
    """ This view will render the form to add meal time """

    day = get_object_or_404(Day, pk=day_id)
    if request.method != "POST":
        # No Data Submitted; create blank form
        form = MealTimeForm()
    else:
        # POST Data Submitted; process data
        form = MealTimeForm(data=request.POST)
        if form.is_valid():
            new_meal_time = form.save(commit=False)
            new_meal_time.day = day
            new_meal_time.save()
            return HttpResponseRedirect(reverse('meal_time', args=[day_id]))
    
    context = {'day':day, 'form':form}
    return render(request, 'meal_planners/add_meal_time.html', context)


def add_meal(request, meal_time_id):
    """ This view will render the form to add meal """

    meal_time = get_object_or_404(MealTime, pk=meal_time_id)
    day = meal_time.day
    if request.method != 'POST':
        # No Data Submitted; create blank form
        form = MealForm()
    else:
        # POST Data Submitted; process data
        form = MealForm(data=request.POST)
        if form.is_valid():
            new_meal = form.save(commit=False)
            new_meal.meal_time = meal_time
            new_meal.save()
            return HttpResponseRedirect(reverse('meal_time', args=[day.id]))
        
    context = {'meal_time':meal_time, 'form':form}
    return render(request, 'meal_planners/add_meal.html', context)
        

accounts/templates/accounts/login.html
{% extends 'meal_planners/base.html' %}

{% block content %}

    <form action="{% url 'login_view' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Log in</button>
    </form>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'meal_planners/base.html' %}

{% block content %}

    <div>
        <h2>REGISTER: </h2>
    </div>

    <div>
        <form action="{% url 'register' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">Register</button>
        </form>
    </div>

{% endblock %}

meal_planners/templates/meal_planners/add_day.html
{% extends 'meal_planners/base.html' %}

{% block content %}

    <div>
        <h2>Add Day: </h2>
    </div>

    <div>
        <form action="{% url 'add_day' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Add Day</button>
        </form>
    </div>

{% endblock %}

meal_planners/templates/meal_planners/add_meal.html
{% extends 'meal_planners/base.html' %}

{% block content %}

    <form action="{% url 'add_meal' meal_time.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Add Meal</button>
    </form>

{% endblock %}

meal_planners/templates/meal_planners/add_meal_time.html
{% extends 'meal_planners/base.html' %}

{% block content %}

    <form action="{% url 'add_meal_time' day.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Add Meal Time</button>
    </form>

{% endblock %}

meal_planners/templates/meal_planners/base.html
<!DOCTYPE html>
<html>
    <div>
        <a href="{% url 'home' %}">Home</a> -
        {% if user.is_authenticated %}
            <a href="{% url 'planner' %}">Planner</a> -
            <a href="{% url 'logout_view' %}">Log out</a> -
        {% else %}
            <a href="{% url 'login_view' %}">Log in</a> -
            <a href="{% url 'register' %}">Register</a>
        {% endif %}

    </div>
    {% block content %}{% endblock %}
</html>

meal_planners/templates/meal_planners/day_meal_plan.html
{% extends 'meal_planners/base.html' %}

{% block content %}

    <head>
        <title>Day Meal Plan</title>
    </head>

    <body>

        <div>
            <h2>{{ day.text|linebreaks }}</h2>
        </div>

        <div>
            <a href="{% url 'add_meal_time' day.id %}">Add Meal Time: </a>
        </div>

        <div>
            <ul>
                {% for meal_time in meal_times %}
                    <li><a href="{% url 'add_meal' meal_time.id %}">{{ meal_time.text }}</a> :
                        {% for meal in meal_time.meal_set.all %}
                            {{ meal.text }}
                        {% endfor %}
                    </li> </br>
                {% empty %}
                    <li>No day meal times yet.</li>
                {% endfor %}
            </ul>
        </div>

    </body>

{% endblock %}

meal_planners/templates/meal_planners/home.html
{% extends 'meal_planners/base.html' %}

{% block content %}

    <head>
        <title>Meal Planner</title>
    </head>

    <body>
        <h1>MEAL PLANNER</h1>
        <div>
            <p>This is a meal planner site home page</p>
        </div>
    </body>

{% endblock %}

meal_planners/templates/meal_planners/planner.html
{% extends 'meal_planners/base.html' %}

{% block content %}

    <head>
        <title>Planner</title>
    </head>

    <body>
        
        <div>
            <a href="{% url 'add_day' %}">Add Day</a>
        </div>
        
        <div>
            <ul>
                {% for day in days %}
                    <li>
                        <a href="{% url 'meal_time' day.id %}">{{ day.text|linebreaks }}</a>
                    </li>
                {% empty %}
                    <li>No Scheduled meal plan.</li>
                {% endfor %}
            </ul>
        </div>
    </body>

{% endblock %}